title: Craig Fisk
logo: /assets/img/headshot_circle.png
description: Available for senior advisor contract work. Former Intel software product line manager and strategy chair, CEO of Series A, Gaia Software, which sold mobile CRM projects from agriculture to cosmetics; CEO of Marmalade AI, pre-seed company applying unsupervised machine learning for automatic, accurate specialist networking. University of Chicago MBA, University of Wisconsin PhD, Fulbright Fellow. https://www.linkedin.com/in/craigfisk, resume at https://craigfisk.com/craigfisk_resume_senior_advisor_2023-11-11.pdf_
#show_downloads: true
theme: jekyll-theme-minimal
