title: Craig Fisk
logo: /assets/img/headshot_circle.png
description: Available for senior advisor contracting. Former Intel software tools manager and strategy chair, CEO of Series A, Gaia Software, which dealt in mobile CRM from agriculture to cosmetics; CEO of Marmalade AI, pre-seed unsupervised ML for automatic, accurate specialist networking. Univ. Chicago MBA, Univ. Wisconsin PhD, Fulbright. 
#show_downloads: true
theme: jekyll-theme-minimal
